Fix build with Qt5.11 (missing QGLFormat header w/ AvogadroLibs support)
Summary:
```
/var/tmp/portage/kde-apps/kalzium-18.03.90/work/kalzium-18.03.90/src/kalzium.cpp: In member function ‘MoleculeDialog* Kalzium::slotMoleculeviewer()’:
/var/tmp/portage/kde-apps/kalzium-18.03.90/work/kalzium-18.03.90/src/kalzium.cpp:381:10: error: ‘QGLFormat’ has not been declared
     if (!QGLFormat::hasOpenGL()) {
          ^~~~~~~~~
```

QGLFormat is used in the following ifdef-block:
```
#if defined(HAVE_OPENBABEL2) && defined(HAVE_EIGEN) && defined(HAVE_AVOGADRO)

    if (!QGLFormat::hasOpenGL()) {
        QMessageBox::critical(Q_NULLPTR, i18n("Kalzium Error"), i18n("This system does not support OpenGL."));
        return NULL;
    }
```

Reviewers: #kde_edu, aacid

Reviewed By: aacid

Tags: #kde_edu

Differential Revision: https://phabricator.kde.org/D12038