Alex asked me to test if I could remove all those ocaml_mli_to_cmi() calls. I cannot see any difference beside that fact that
 Generating /home/carsten/svn/trunk/kdeedu/kalzium/src/solver/calc.cmi

et al is no longer generated. It still get the crash 

#5  0x0813f9f6 in caml_alloc_string ()
#6  0x0813fa6a in caml_copy_string ()
#7  0x0813cfeb in solve_equation ()
#8  0x080d8df4 in EQChemDialog::compute (this=0x889c990)
    at /home/carsten/svn/trunk/kdeedu/kalzium/src/eqchemview.cpp:52

and now guess it has something to do with this compiler-warning:

 /src/solver/modwrap.c: In function ‘solve_equation’:
 /src/solver/modwrap.c:35: warning: implicit declaration of function ‘caml_copy_string’

CCMAIL: montel@kde.org
CCMAIL: neundorf@kde.org

svn path=/trunk/KDE/kdeedu/kalzium/; revision=597393